#!/bin/bash
tmp_download_dir="$(mktemp -d -t 'asdf_loki_XXXXXX')"
trap 'rm -rf "${tmp_download_dir}"' EXIT

_install(){
	echo $@
}
_install "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH" "$tmp_download_dir"

asdf reshim "$(plugin_name)" "$ASDF_INSTALL_VERSION"